version: "3"

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - APP_URL=${RAILWAY_STATIC_URL}
      - DB_CONNECTION=mysql
      - DB_URL=${MYSQL_URL}
      - SESSION_DRIVER=database
      - CACHE_DRIVER=database
      - QUEUE_CONNECTION=database
